algo = input('Digite algo: ')
print(f'Só tem espaços? {algo.isspace()}')
print(f'É numérico? {algo.isnumeric()}')
print(f'É alfabético? {algo.isalpha()}')
print(f'É alfanumérico? {algo.isalnum()}')
print(f'Está em letras maiúsculas? {algo.isupper()}')
print(f'Está em letras minúsculas? {algo.islower()}')
print(f'Está capitalizada? {algo.istitle()}')